// Command features configuration
// This file stores the feature flags for commands (hasExamples, hasOnlineExecution)
export const commandFeatures: Record<string, { hasExamples?: boolean; hasOnlineExecution?: boolean }> = {
  "/cast-4byte": { hasExamples: false },
  "/cast-4byte-calldata": { hasExamples: false },
  "/cast-4byte-event": { hasExamples: false },
  "/cast-abi-encode": { hasExamples: true, hasOnlineExecution: true },
  "/cast-calldata": { hasExamples: true, hasOnlineExecution: true },
  "/cast-decode-abi": { hasExamples: true, hasOnlineExecution: true },
  "/cast-decode-calldata": { hasExamples: true, hasOnlineExecution: true },
  "/cast-decode-error": { hasExamples: false },
  "/cast-decode-event": { hasExamples: false },
  "/cast-decode-string": { hasExamples: false },
  "/cast-pretty-calldata": { hasExamples: false },
  "/cast-selectors": { hasExamples: false },
  "/cast-upload-signature": { hasExamples: false },
  "/cast-format-bytes32-string": { hasExamples: false },
  "/cast-format-units": { hasExamples: false },
  "/cast-from-bin": { hasExamples: false },
  "/cast-from-fixed-point": { hasExamples: false },
  "/cast-from-rlp": { hasExamples: false },
  "/cast-from-utf8": { hasExamples: false },
  "/cast-from-wei": { hasExamples: true, hasOnlineExecution: true },
  "/cast-parse-bytes32-address": { hasExamples: false },
  "/cast-parse-bytes32-string": { hasExamples: false },
  "/cast-parse-units": { hasExamples: false },
  "/cast-to-ascii": { hasExamples: false },
  "/cast-to-base": { hasExamples: false },
  "/cast-to-bytes32": { hasExamples: true, hasOnlineExecution: true },
  "/cast-to-dec": { hasExamples: true, hasOnlineExecution: true },
  "/cast-to-fixed-point": { hasExamples: false },
  "/cast-to-hex": { hasExamples: true, hasOnlineExecution: true },
  "/cast-to-hexdata": { hasExamples: false },
  "/cast-to-int256": { hasExamples: false },
  "/cast-to-rlp": { hasExamples: false },
  "/cast-to-uint256": { hasExamples: false },
  "/cast-to-unit": { hasExamples: true, hasOnlineExecution: true },
  "/cast-to-utf8": { hasExamples: false },
  "/cast-to-wei": { hasExamples: false },
  "/cast-shl": { hasExamples: false },
  "/cast-shr": { hasExamples: false },
  "/cast-address-zero": { hasExamples: false },
  "/cast-sig": { hasExamples: false },
  "/cast-sig-event": { hasExamples: false },
  "/cast-keccak": { hasExamples: true, hasOnlineExecution: true },
  "/cast-hash-message": { hasExamples: false },
  "/cast-hash-zero": { hasExamples: false },
  "/cast-compute-address": { hasExamples: false },
  "/cast-create2": { hasExamples: false },
  "/cast-interface": { hasExamples: false },
  "/cast-bind": { hasExamples: false },
  "/cast-artifact": { hasExamples: false },
  "/cast-index": { hasExamples: false },
  "/cast-index-erc7201": { hasExamples: false },
  "/cast-concat-hex": { hasExamples: false },
  "/cast-max-int": { hasExamples: false },
  "/cast-min-int": { hasExamples: false },
  "/cast-max-uint": { hasExamples: false },
  "/cast-to-check-sum-address": { hasExamples: false },
  "/cast-generate-fig-spec": { hasExamples: false },
  "/cast-completions": { hasExamples: false },
  "/cast-disassemble": { hasExamples: false },
  "/cast-recover-authority": { hasExamples: false },
  "/cast-chain-id": { hasExamples: true, hasOnlineExecution: false },
  "/cast-chain": { hasExamples: true },
  "/cast-client": { hasExamples: true, hasOnlineExecution: false },
  "/cast-access-list": { hasExamples: false, hasOnlineExecution: false },
  "/cast-call": { hasExamples: false, hasOnlineExecution: false },
  "/cast-estimate": { hasExamples: false, hasOnlineExecution: false },
  "/cast-logs": { hasExamples: false },
  "/cast-mktx": { hasExamples: false },
  "/cast-publish": { hasExamples: false },
  "/cast-receipt": { hasExamples: true },
  "/cast-rpc": { hasExamples: false, hasOnlineExecution: false },
  "/cast-run": { hasExamples: false, hasOnlineExecution: false },
  "/cast-send": { hasExamples: false, hasOnlineExecution: false },
  "/cast-tx": { hasExamples: false, hasOnlineExecution: false },
  "/cast-decode-transaction": { hasExamples: false },
  "/cast-da-estimate": { hasExamples: false },
  "/cast-age": { hasExamples: false },
  "/cast-base-fee": { hasExamples: false },
  "/cast-block": { hasExamples: false },
  "/cast-block-number": { hasExamples: false },
  "/cast-find-block": { hasExamples: false },
  "/cast-gas-price": { hasExamples: false },
  "/cast-balance": { hasExamples: false },
  "/cast-nonce": { hasExamples: false },
  "/cast-code": { hasExamples: false },
  "/cast-codehash": { hasExamples: false },
  "/cast-codesize": { hasExamples: false },
  "/cast-storage": { hasExamples: false },
  "/cast-storage-root": { hasExamples: false },
  "/cast-proof": { hasExamples: false },
  "/cast-admin": { hasExamples: false },
  "/cast-implementation": { hasExamples: false },
  "/cast-creation-code": { hasExamples: false },
  "/cast-constructor-args": { hasExamples: false },
  "/cast-lookup-address": { hasExamples: false },
  "/cast-resolve-name": { hasExamples: false },
  "/cast-namehash": { hasExamples: false },
  "/cast-source": { hasExamples: false },
  "/cast-tx-pool": { hasExamples: false },
  "/cast-tx-pool-content": { hasExamples: false },
  "/cast-tx-pool-content-from": { hasExamples: false },
  "/cast-tx-pool-inspect": { hasExamples: false },
  "/cast-tx-pool-status": { hasExamples: false },
  "/cast-wallet": { hasExamples: false },
  "/cast-wallet-new": { hasExamples: false },
  "/cast-wallet-new-mnemonic": { hasExamples: false },
  "/cast-wallet-address": { hasExamples: false },
  "/cast-wallet-sign": { hasExamples: false },
  "/cast-wallet-sign-auth": { hasExamples: false },
  "/cast-wallet-vanity": { hasExamples: false },
  "/cast-wallet-verify": { hasExamples: false },
  "/cast-wallet-import": { hasExamples: false },
  "/cast-wallet-list": { hasExamples: false },
  "/cast-wallet-private-key": { hasExamples: false },
  "/cast-wallet-public-key": { hasExamples: false },
  "/cast-wallet-decrypt-keystore": { hasExamples: false },
  "/cast-wallet-remove": { hasExamples: false },
  "/cast-wallet-change-password": { hasExamples: false },
};