[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --no-scripts"]

[phases.build]
cmds = ["NEXT_TELEMETRY_DISABLED=1 npm run build --no-lint"]

[start]
cmd = "npm run start"