# This file configures the Nixpacks build environment.
# For more information, see: https://nixpacks.com/docs/configuration/file

[phases.setup]
# By adding "git" here, we ensure that a modern version of Git from the
# Nix packages repository is installed in the build container before any
# build commands are run. This resolves deployment failures caused by
# outdated Git clients that do not recognize modern flags.
nixPkgs = ["git"]

[phases.install]
cmds = ["npm install --force"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"